apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: web         
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
      - name: init-page
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            if [ ! -f /usr/share/nginx/html/index.html ]; then
              echo "Hello from $(hostname)" > /usr/share/nginx/html/index.html
              date >> /usr/share/nginx/html/index.html
            fi
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
